Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
  AccommodationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Accommodation"
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "AccessibilityNeed"
          AttributeType: "S"
        - AttributeName: "Accommodations"
          AttributeType: "SS"

      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
#  InitFunction:
#    Type: AWS::Lambda::Function
#    Properties:
#      Code:
#        ZipFile: >
#          const AWS = require("aws-sdk");
#          const response = require('./cfn-response');
#          const docClient = new AWS.DynamoDB.DocumentClient();
#          exports.handler = function(event, context) {
#            console.log(JSON.stringify(event,null,2));
#            var params = {
#              RequestItems: {
#                "Accommodation": [
#                  {
#                    PutRequest: {
#                      Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels", "Mets", "Jersey"
#
#                      }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                         Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                      }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                         Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                      }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                         Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                      }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                      Item: {
#                              Id: "2020-10-07",
#                              AccessibilityNeed: "6",
#                              Accommodations: "Angels",
#
#                                        }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                      Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                                        }
#                      }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                      Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                                        }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                      Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                                        }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                      Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                                        }
#                    }
#                  },
#                  {
#                    PutRequest: {
#                         Item: {
#                        Id: "2020-10-07",
#                        AccessibilityNeed: "6",
#                        Accommodations: "Angels",
#
#                      }
#                    }
#                  }
#                ]
#              }
#            };
#            docClient.batchWrite(params, function(err, data) {
#              if (err) {
#                response.send(event, context, "FAILED", {});
#              } else {
#                response.send(event, context, "SUCCESS", {});
#              }
#            });
#          };
#      Handler: index.handler
#      Role:
#        Fn::GetAtt: [ LambdaRole , "Arn" ]
#      Runtime: nodejs12.x
#      Timeout: 60
#  InitializeLeagueMatchesTable:
#    Type: Custom::InitFunction
#    DependsOn: AccommodationsTable
#    Properties:
#      ServiceToken:
#        Fn::GetAtt: [ InitFunction , "Arn" ]
#      DynamoTableName:
#        Ref: AccommodationsTable
